(define-resource recipe ()
    :class (s-prefix "schema:Recipe")
    :properties `((:title :string ,(s-prefix "schema:name"))
                (:description :string ,(s-prefix "schema:abstract"))
                (:duration :string ,(s-prefix "schema:cookTime"))
                (:category :string ,(s-prefix "schema:recipeCategory"))
                (:cuisine :string ,(s-prefix "schema:recipeCuisine"))
                (:ingredient :string ,(s-prefix "schema:recipeIngredient"))
                (:yield :string ,(s-prefix "schema:recipeYield"))
                (:diet :uri ,(s-prefix "schema:suitableForDiet")))
    :has-one `((user :via ,(s-prefix "schema:creator")
                       :as "creator")
                (instructions :via ,(s-prefix "schema:recipeInstructions")
                            :as "instructions"))
    :resource-base (s-url "http://mu.semte.ch/graphs/recipes/")
    :on-path "recipes")

(define-resource instructions ()
    :class (s-prefix "schema:itemList")
    :properties `((:step :string ,(s-prefix "schema:itemListElement")))
    :has-one `((recipe :via ,(s-prefix "schema:recipeInstructions")
                        :inverse t
                        :as "recipe"))
    :resource-base (s-url "http://mu.semte.ch/graphs/recipes/instructions/")
    :on-path "instructions")

